name: docker-complete-workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Docker:    
    runs-on: ubuntu-latest
    name: "Docker Workflow"
    steps:
      - name: checking out code
        uses: actions/checkout@v2.3.4
      - name: Generate semantic version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: main
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Next semantic version
        if: steps.semantic.outputs.new_release_version == ''
        run: | 
           echo "ERROR => failed to fetch new semantic version, exiting..."
           exit 1
      - name: Linting Dockerfile with hadolint
        uses: brpaz/hadolint-action@v1.1.0
      - name: Build Docker Image
        run: |
          docker build -t ubuntu:v${{ steps.semantic.outputs.new_release_version }} .
      - name: Install inspec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - name: Auditing Docker Image
        run: |
          inspec exec --chef-license=accept docker.rb
      - name: Install dgoss
        uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: v0.3.9
      - name: Run Dockerfile test cases
        run: |
          dgoss run ubuntu:v${{ steps.semantic.outputs.new_release_version }}
      - name: Trivy to scan Docker image
        uses: lazy-actions/gitrivy@v2
        with:
          image: ubuntu:v${{ steps.semantic.outputs.new_release_version }}
          token: ${{ secrets.GIT_TOKEN }}
          issue_title: Security_Alert
          issue_label: trivy,vulnerability
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: ubuntu:v${{ steps.semantic.outputs.new_release_version }}
          is-semver: false # will push my-image:1, my-image:1.2 and my-image:1.2.3
