name: node-js-workflow
on:
  push:
    branches:  
      - main
      - feature/**
  pull_request:
    branches: [ main ]
jobs:
       
  BuildNotificationSuccess:
    name: MSTeamBuildStatusSuccess
    runs-on: ubuntu-latest
    #needs: NodeJS
    #if: always()
    steps:
      - name: send success notification to MSTeam
        uses: skitionek/notify-microsoft-teams@v1.0.4
        if: success()
        with:
          webhook_url: "${{ secrets.MSTEAM_WEBHOOK }}"
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          raw: ${{ toJson(github.repository) }}
