on: [push]

jobs:

  SonarBuildBreaker:

    runs-on: ubuntu-latest

    name: SonarBuildBreaker

    steps:

      - name: Code Checkout

        uses: actions/checkout@v2

      - name: GitHub Pipeline Start Alert

        uses: toko-bifrost/ms-teams-deploy-card@3.1.2

        with:

          github-token: ${{ secrets.GIT_TOKEN }}

          webhook-uri: ${{ secrets.MSTEAM_WEBHOOK }}

  
