on: [push]

jobs:

  SonarBuildBreaker:

    runs-on: ubuntu-latest

    name: SonarBuildBreaker

    steps:

      - name: Code Checkout

        uses: actions/checkout@v2

      - name: GitHub Pipeline Start Alert

        uses: toko-bifrost/ms-teams-deploy-card@3.1.2

        with:

          github-token: ${{ secrets.GIT_TOKEN }}

          webhook-uri: ${{ secrets.MSTEAM_WEBHOOK }}
          card-layout-start: complete
          card-layout-exit: complete
          show-on-start: true
          show-on-exit: true
          show-on-failure: true
          environment: development
          custom-facts: |
            - name: JobStatus
              value: ${{ job.status }}
          custom-actions: |
            - text: View PR
              url: "https://github.com/bhojrajjoshi2020/nodejs-semver/actions/runs/${{ github.run_id }}"
  
