name: node-js-workflow
on:
  push:
    branches:  
      - main
      - feature/**
  pull_request:
    branches: [ main ]
jobs:
  NodeJS:    
    runs-on: self-hosted
    name: "NodeJS Workflow"
    steps:
      - name: "[1] code checkout"
        uses: actions/checkout@v2.3.4
      - name: GitHub Pipeline Alerts
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          webhook-uri: ${{ secrets.MSTEAM_WEBHOOK }}
          card-layout-start: complete
          card-layout-exit: complete
          show-on-start: true
          show-on-exit: true
          environment: development
          custom-facts: |
            - name: Initiated by
              value: ${{ github.actor }}
            - name: Workflow name
              value: ${{ github.workflow }}
          custom-actions: |
            - text: View Job Execution Status
              url: "https://github.com/bhojrajjoshi2020/nodejs-semver/actions/runs/${{ github.run_id }}"
