name: node-js-workflow
on:
  push:
    branches:  
      - main
      - feature/**
  pull_request:
    branches: [ main ]
jobs:
  NodeJS:    
    runs-on: ubuntu-latest
    name: "NodeJS Workflow"
    steps:
      - name: "[1] code checkout"
        uses: actions/checkout@v2.3.4
      - uses: brpaz/action-semantic-release@v1
        with:
          dry_run: "true"
          install_plugins: "semantic-release-npm"
          branch: main
      - name: "[2] calculate semantic version"
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branches: feature/test3
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: "[14] push to image to ECR"
        id: ecr
        uses: jwalton/gh-ecr-push@v1.0.0
        with:
          access-key-id: ${{ secrets.PERSONAL_AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.PERSONAL_AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: nodejs-semver-repo:v${{ steps.semantic.outputs.new_release_version }}
  BuildNotification:
    name: MSTeamBuildStatus
    runs-on: ubuntu-latest
    needs: NodeJS
    if: always()
    steps:
      - name: set notification to MSTeam
        uses: skitionek/notify-microsoft-teams@v1.0.4
        if: always()
        with:
          webhook_url: "${{ secrets.MSTEAM_WEBHOOK }}"
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }} 
